"""
SQLite persistence layer for the KPI Forecasting & Alerting Dashboard.

Three tables:
- kpi_history: raw daily actuals per metric (the "ground truth" time series)
- forecasts:   forecast points generated by a given method, with confidence bounds
- alerts:      backtested deviations where an actual value fell outside a
               previously generated forecast's confidence band

Using SQLite (instead of in-memory / flat files) is the main step-up from
Day 3: forecasts and alerts persist across app restarts, and the dashboard
reads/writes through this module instead of holding everything in process
memory.
"""

import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone

SCHEMA = """
CREATE TABLE IF NOT EXISTS kpi_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    metric TEXT NOT NULL,
    date TEXT NOT NULL,
    value REAL NOT NULL,
    UNIQUE(metric, date)
);

CREATE TABLE IF NOT EXISTS forecasts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    metric TEXT NOT NULL,
    method TEXT NOT NULL,
    date TEXT NOT NULL,
    forecast_value REAL NOT NULL,
    lower_bound REAL NOT NULL,
    upper_bound REAL NOT NULL,
    generated_at TEXT NOT NULL,
    UNIQUE(metric, method, date, generated_at)
);

CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    metric TEXT NOT NULL,
    date TEXT NOT NULL,
    actual_value REAL NOT NULL,
    forecast_value REAL NOT NULL,
    lower_bound REAL NOT NULL,
    upper_bound REAL NOT NULL,
    severity TEXT NOT NULL,
    method TEXT NOT NULL,
    generated_at TEXT NOT NULL
);
"""


def get_connection(db_path):
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


@contextmanager
def connect(db_path):
    conn = get_connection(db_path)
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def init_db(conn):
    conn.executescript(SCHEMA)
    conn.commit()


def now_iso():
    # Microsecond precision avoids generated_at collisions when forecasts
    # are regenerated back-to-back (e.g. one manual /api/forecast call
    # immediately followed by /api/refresh) within the same second.
    return datetime.now(timezone.utc).isoformat(timespec="microseconds")


# ---------------------------------------------------------------- history --

def upsert_history(conn, metric, rows):
    """rows: iterable of (date_str, value)"""
    conn.executemany(
        """INSERT INTO kpi_history (metric, date, value)
           VALUES (?, ?, ?)
           ON CONFLICT(metric, date) DO UPDATE SET value = excluded.value""",
        [(metric, d, v) for d, v in rows],
    )
    conn.commit()


def get_metrics(conn):
    cur = conn.execute("SELECT DISTINCT metric FROM kpi_history ORDER BY metric")
    return [r["metric"] for r in cur.fetchall()]


def get_history(conn, metric, limit=None):
    q = "SELECT date, value FROM kpi_history WHERE metric = ? ORDER BY date ASC"
    cur = conn.execute(q, (metric,))
    rows = [(r["date"], r["value"]) for r in cur.fetchall()]
    if limit:
        rows = rows[-limit:]
    return rows


# --------------------------------------------------------------- forecasts --

def save_forecast(conn, metric, method, rows):
    """rows: iterable of (date_str, forecast_value, lower_bound, upper_bound)"""
    ts = now_iso()
    conn.executemany(
        """INSERT INTO forecasts (metric, method, date, forecast_value,
                                   lower_bound, upper_bound, generated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(metric, method, date, generated_at) DO UPDATE SET
               forecast_value = excluded.forecast_value,
               lower_bound = excluded.lower_bound,
               upper_bound = excluded.upper_bound""",
        [(metric, method, d, fv, lo, hi, ts) for d, fv, lo, hi in rows],
    )
    conn.commit()
    return ts


def get_latest_forecast(conn, metric, method):
    cur = conn.execute(
        """SELECT generated_at FROM forecasts
           WHERE metric = ? AND method = ?
           ORDER BY generated_at DESC LIMIT 1""",
        (metric, method),
    )
    row = cur.fetchone()
    if not row:
        return []
    generated_at = row["generated_at"]
    cur = conn.execute(
        """SELECT date, forecast_value, lower_bound, upper_bound
           FROM forecasts
           WHERE metric = ? AND method = ? AND generated_at = ?
           ORDER BY date ASC""",
        (metric, method, generated_at),
    )
    return [dict(r) for r in cur.fetchall()]


# ------------------------------------------------------------------ alerts --

def clear_alerts(conn, metric=None):
    if metric:
        conn.execute("DELETE FROM alerts WHERE metric = ?", (metric,))
    else:
        conn.execute("DELETE FROM alerts")
    conn.commit()


def save_alerts(conn, alerts):
    """alerts: iterable of dicts with keys metric, date, actual_value,
    forecast_value, lower_bound, upper_bound, severity, method"""
    ts = now_iso()
    conn.executemany(
        """INSERT INTO alerts (metric, date, actual_value, forecast_value,
                                lower_bound, upper_bound, severity, method,
                                generated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        [
            (
                a["metric"], a["date"], a["actual_value"], a["forecast_value"],
                a["lower_bound"], a["upper_bound"], a["severity"], a["method"], ts,
            )
            for a in alerts
        ],
    )
    conn.commit()
    return ts


def get_alerts(conn, metric=None):
    if metric:
        cur = conn.execute(
            "SELECT * FROM alerts WHERE metric = ? ORDER BY date DESC", (metric,)
        )
    else:
        cur = conn.execute("SELECT * FROM alerts ORDER BY date DESC")
    return [dict(r) for r in cur.fetchall()]
